### ISSUE TITLE
length in a union

### ISSUE THREAD

**Issue by jcourington** [corenova/yang-js#102]
Thank you very much for the quick responses on these issues. My models compile after this issue!

```
typedef t_A {
  type union {
    type string P
      length 4;
      pattern '[a-fA-F0-9]*';
    }
    type string {
      length 6;
      pattern '[a-fA-F0-9]*';
    }
  }
}
```

results in

```
ExpressionError: [submodule()/grouping()/leaf()/type(t_A)/type(string)] constraint violation for 'length' - cannot define more than once
    at Function.Element.error (/home/src/node_modules/yang-js/lib/element.js:60:15)
    at Function.Expression.error (/home/src/node_modules/yang-js/lib/expression.js:191:40)
    at Function.Element.merge (/home/src/node_modules/yang-js/lib/element.js:339:24)
    at Function.Yang.merge (/home/src/node_modules/yang-js/lib/yang.js:352:39)
    at Function.Element.update (/home/src/node_modules/yang-js/lib/element.js:402:21)
    at Function.Expression.update (/home/src/node_modules/yang-js/lib/expression.js:184:41)
    at Function.Element.update (/home/src/node_modules/yang-js/lib/element.js:407:16)
    at Function.Expression.update (/home/srcnode_modules/yang-js/lib/expression.js:184:41)
    at Function.Element.update (/home/src/node_modules/yang-js/lib/element.js:407:16)
    at Function.Expression.update (/home/src/node_modules/yang-js/lib/expression.js:184:41)
```

**Comment by saintkepha** [comment]
Hi @jcourington - unfortunately there isn't a quick fix for this issue due to the way current parser uses the `tag` to internally cache key lookup mappings.

However, here's a workaround that should satisfy your intended `typedef`:
```
typedef alpha-numeric-string {
  type string {
    pattern '[a-fA-F0-9]*';
  }
}
typedef fixed-string-4 {
  type alpha-numeric-string {
    length 4;
  } 
}
typedef fixed-string-6 {
  type alpha-numeric-string {
    length 6;
  }
}
typedef t_A {
  type union {
    type fixed-string-4;
    type fixed-string-6;
  }
}
```
I'll leave this issue open since we should properly handle the exception case for `type` that can have multiple duplicate tag values.

**Comment by jcourington** [comment]
Hi Peter,

 I have figured out containers. I see now that there is an array of leafs under a container. I can access everything in my model.
 I really appreciate your help working through everything.

Let me know if this example could help others...

Thank you,

Jeff

________________________________

**Comment by saintkepha** [comment]
@jcourington - my initial assessment on this issue was incorrect. I've added testcases for this scenario and it doesn't appear that this is an issue related to `tag` merge inside `typedef`. The `tag` merge constraint only applies to data nodes `container, list, leaf, leaf-list`.

I suspect something related to parsing with `{ compile: false }` since when we process `type` we perform implicit `compile()`... but this is just a guess at this point.

I'll close this issue for now, but please let me know if this issue persists for you.
