### ISSUE TITLE
Length and Pattern properties are not handled properly for String type

### ISSUE THREAD

**Issue by pnuzhdin** [corenova/yang-js#2]
For following example:
```
var test = require('yang-js').load(`
  module test {
    prefix "test";

    leaf ttt {
        type string {
            length 1;
        };
    }
  }
`)
```

I have had following error:
```
YinError: must pass in proper 'schema' to preprocess
  at Yin.Origin.error (/notebooks/node_modules/yang-js/lib/origin.js:171:13)
  at Yin.error (/notebooks/node_modules/yang-js/lib/yin.js:257:33)
  at Yin.preprocess (/notebooks/node_modules/yang-js/lib/yin.js:393:20)
  at Yin.compile (/notebooks/node_modules/yang-js/lib/yin.js:296:20)
  at /notebooks/node_modules/yang-js/lib/yin.js:246:34
  at Array.forEach (native)
  at Yin.use (/notebooks/node_modules/yang-js/lib/yin.js:244:49)
  at Yin.load (/notebooks/node_modules/yang-js/lib/yin.js:153:39)
```

**Comment by saintkepha** [comment]
I'm not sure that the issue is due to invalid handling of length statement for string type.  I'll take a closer look at what the underlying issue is.

**Comment by saintkepha** [comment]
0.14.0 published, please give it a try
