### ISSUE TITLE
Parse should not die silently

### ISSUE THREAD

**Issue by pnuzhdin** [corenova/yang-js#3]
Currently, parse returns the same invalid schema instead of throwing an error.
So for following example:
```
var test = require('yang-js').parse(`
  module test {
    prefix "test";

    asd
  }
`)
```

```test``` will have 'module test { prefix "test";\nasd }' but load will return following:

```
YinError: must pass in proper 'schema' to preprocess
  at Yin.Origin.error (/notebooks/node_modules/yang-js/lib/origin.js:171:13)
  at Yin.error (/notebooks/node_modules/yang-js/lib/yin.js:257:33)
  at Yin.preprocess (/notebooks/node_modules/yang-js/lib/yin.js:393:20)
  at Yin.compile (/notebooks/node_modules/yang-js/lib/yin.js:296:20)
  at /notebooks/node_modules/yang-js/lib/yin.js:246:34
  at Array.forEach (native)
  at Yin.use (/notebooks/node_modules/yang-js/lib/yin.js:244:49)
  at Yin.load (/notebooks/node_modules/yang-js/lib/yin.js:153:39)
```

**Comment by saintkepha** [comment]
Please refer to my reply in #4.  The upcoming update will address this issue.
