### ISSUE TITLE
yang-express failed to enable feature on the latest yang-js

### ISSUE THREAD

**Issue by quantang** [corenova/yang-js#75]
Tried the lastest yang-js, it is awesome.
However, the yang-express cannot work anymore, which fails to enable a feature. I guess it would be a bug in the latest yang-js, so I open the issue here.

Here is the error message:
```
2018-10-12 11:21:38+1300: Yang Express failed to start: PropertyError: [/yang-express] unable to enable unknown feature 'restjson'
    at Model.Property.error (/home/quant/Projects/vistamanager/node_modules/yang-js/lib/property.js:387:13)
    at Model.enable (/home/quant/Projects/vistamanager/node_modules/yang-js/lib/model.js:117:20)
    at Object.proto.(anonymous function) [as enable] (/home/quant/Projects/vistamanager/node_modules/delegates/index.js:40:31)
    at Object.run (/home/quant/Projects/vistamanager/node_modules/yang-express/lib/yang-express.js:35:14)
    at Method.do (/home/quant/Projects/vistamanager/node_modules/yang-js/lib/method.js:79:30)
    at YangService.startServer (/home/quant/Projects/vistamanager/dist/src_server/yang/yangService.ts:51:16)
    at YangService.<anonymous> (/home/quant/Projects/vistamanager/dist/src_server/yang/yangConfig.ts:23:33)
```

**Comment by saintkepha** [comment]
The new "feature" methodology is to treat it as a bindable object. It can be a function or an object with functions. Instead of enabling or disabling, we bind it as needed to denote availability of a given feature. 

In the case of yang-express, we would bind every feature into the yang-express module and then inside the rpc run binding function, *use* the feature based on the features enabled as part of the rpc input arguments. 

I'll take a stab at this tomorrow.

**Comment by saintkepha** [comment]
Working on porting yang-express to ES6. Should have it ready in a couple of days.

**Comment by saintkepha** [comment]
Latest yang-express (after 0.6) is compatible with latest yang-js.
